### ISSUE TITLE
[FEAT] 지도 개발 : FE

### ISSUE THREAD

**Issue by tpdlshdmlrkfmcla** [marso34/ytt-medicine-vending-machine#14]
## 내용(Describe the Feature)
지도 개발

## To-Do
- [x] Fragment 생성
- [x] 메인화면 카카오 지도개발
  - 카카오 api에서 네이버 api로 변경

**Comment by tpdlshdmlrkfmcla** [comment]
![image](https://github.com/user-attachments/assets/4d1f246d-1eb1-4aa9-8119-f3db18e23110)
revert 완료

**Comment by marso34** [comment]
![image](https://github.com/user-attachments/assets/fdecd229-794d-454b-9a6e-5836f2553d89)

<br> 

지도 기능 개발 브랜치에 .idea 디렉터리 또 올라갔어요. 확인해주세요

**Comment by tpdlshdmlrkfmcla** [comment]
![image](https://github.com/user-attachments/assets/db0274b7-e2b2-4f81-80f4-e58e99df7671)


깃이그노어 파일 새로 적용하는 과정에서 스테이징되어있던 파일들이 모두 푸시되었습니다.(커밋메시지무시)
